# Generated by Django 3.1.2 on 2020-10-17 23:08

from django.db import migrations, models
import tinymce.models
import walloffaces.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hometown', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('doc', models.DateField(verbose_name='Date of Casualty')),
                ('branch', models.CharField(max_length=150, verbose_name='Branch of Service')),
                ('rank', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=walloffaces.models.veteran_images)),
                ('bio', tinymce.models.HTMLField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
