# Generated by Django 3.1.2 on 2020-10-18 12:45

from django.db import migrations, models
import walloffaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteran',
            name='bio',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='veteran',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country of Service'),
        ),
        migrations.AlterField(
            model_name='veteran',
            name='image',
            field=models.ImageField(upload_to=walloffaces.models.veteran_images, verbose_name='Headshot'),
        ),
    ]
