# Generated by Django 3.1.2 on 2020-10-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0002_auto_20201018_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteran',
            name='doc',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Casualty'),
        ),
    ]
