# Generated by Django 3.1.2 on 2020-10-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0003_auto_20201018_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteran',
            name='branch',
            field=models.CharField(choices=[('Air Force', 'Air Force'), ('Army', 'Army'), ('Marine Corps', 'Marine Corps'), ('Navy', 'Navy'), ('Space Force', 'Space Force')], max_length=150, verbose_name='Branch of Service'),
        ),
        migrations.AlterField(
            model_name='veteran',
            name='county',
            field=models.CharField(choices=[('Berks', 'Berks'), ('Bucks', 'Bucks'), ('Chester', 'Chester'), ('Delaware', 'Delaware'), ('Lancaster', 'Lancaster'), ('Lehigh', 'Lehigh'), ('Montgomery', 'Montgomery'), ('Northampton', 'Northampton'), ('Philadelphia', 'Philadelphia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='veteran',
            name='status',
            field=models.CharField(choices=[('Living', 'Living'), ('Killed In Action', 'Killed In Action'), ('Missing In Action', 'Missing In Action'), ('Remains Recovered', 'Remains Recovered'), ('Deceased', 'Deceased')], max_length=50),
        ),
    ]
