# Generated by Django 3.1.2 on 2020-10-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0004_auto_20201026_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remembrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('remembrance', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(choices=[('Husband', 'Husband'), ('Wife', 'Wife'), ('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Cousin', 'Cousin'), ('Served Together', 'Served Together'), ('College Classmates', 'College Classmates'), ('Grew Up Together', 'Grew Up Together'), ('Close Friends', 'Close Friends'), ('Other', 'Other')], max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walloffaces.veteran')),
            ],
        ),
    ]
