# Generated by Django 3.1.2 on 2020-10-27 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0005_remembrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='remembrance',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remembrance',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Your Email'),
        ),
        migrations.AlterField(
            model_name='remembrance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='remembrance',
            name='relationship',
            field=models.CharField(choices=[('Husband', 'Husband'), ('Wife', 'Wife'), ('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Cousin', 'Cousin'), ('Served Together', 'Served Together'), ('College Classmates', 'College Classmates'), ('Grew Up Together', 'Grew Up Together'), ('Close Friends', 'Close Friends'), ('Other', 'Other')], max_length=20, verbose_name='Relationship to Veteran'),
        ),
    ]
