# Generated by Django 3.1.2 on 2020-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0006_auto_20201027_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteran',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='veteran',
            name='doc',
            field=models.DateField(blank=True, help_text='Leave blank if veteran is still living', null=True, verbose_name='Date of Casualty'),
        ),
    ]
