# Generated by Django 3.1.2 on 2020-11-01 23:01

from django.db import migrations, models
import walloffaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0007_auto_20201101_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteran',
            name='adtl_img_1',
            field=models.ImageField(blank=True, null=True, upload_to=walloffaces.models.veteran_images, verbose_name='Additional Image 1'),
        ),
        migrations.AddField(
            model_name='veteran',
            name='adtl_img_2',
            field=models.ImageField(blank=True, null=True, upload_to=walloffaces.models.veteran_images, verbose_name='Additional Image 2'),
        ),
        migrations.AddField(
            model_name='veteran',
            name='adtl_img_3',
            field=models.ImageField(blank=True, null=True, upload_to=walloffaces.models.veteran_images, verbose_name='Additional Image 3'),
        ),
        migrations.AddField(
            model_name='veteran',
            name='adtl_img_4',
            field=models.ImageField(blank=True, null=True, upload_to=walloffaces.models.veteran_images, verbose_name='Additional Image 4'),
        ),
        migrations.AddField(
            model_name='veteran',
            name='adtl_img_5',
            field=models.ImageField(blank=True, null=True, upload_to=walloffaces.models.veteran_images, verbose_name='Additional Image 5'),
        ),
        migrations.AddField(
            model_name='veteran',
            name='adtl_img_6',
            field=models.ImageField(blank=True, null=True, upload_to=walloffaces.models.veteran_images, verbose_name='Additional Image 6'),
        ),
    ]
