# Generated by Django 3.1.2 on 2020-11-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walloffaces', '0008_auto_20201101_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteran',
            name='doc',
            field=models.DateField(blank=True, help_text='Leave blank if veteran is still living', null=True, verbose_name='Date of Death'),
        ),
        migrations.AlterField(
            model_name='veteran',
            name='status',
            field=models.CharField(choices=[('Living', 'Living'), ('Killed In Action', 'Killed In Action'), ('Missing In Action', 'Missing In Action'), ('Remains Recovered', 'Remains Recovered'), ('Deceased (Not in Action)', 'Deceased (Not in Action)')], max_length=50),
        ),
    ]
